const motivationalQuotes = [
    "The most disastrous thing that you can ever learn is your first programming language. - Alan Kay",
    "You are not a computer programmer, you are a problem solver. - Anonymous",
    "First, solve the problem. Then, write the code. - John Johnson",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "The sooner you start to code, the longer the program will take. - Roy Carlson",
    "You might not think that programmers are artists, but programming is an extremely creative profession. - John Romero",
    "Programmers are constantly making things more complicated than they need to be because future-proofing is impossible. - Edsger W. Dijkstra",
    "One of the best programming skills you can have is knowing when to walk away for a while. - Oscar Godson",
    "The best code is the code never written. - Anonymous",
    "If you don’t understand how to run an operating system, you shouldn’t be a programmer. - Richard Stallman",
    "It's not at all important to get it right the first time. It's vitally important to get it right the last time. - Andrew Hunt and David Thomas",
    "The goal of a programmer is to simplify the complexity of a problem. - Anonymous",
    "Coding is not just code, that is a live thing to share your life with. - Anonymous",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Sometimes the best way to learn is to just dive in. - Jon Bonne",
    "The code you write makes you a programmer. The code you delete makes you a good one. - Mario Fusco",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson and Gerald Jay Sussman",
    "We build our computer systems the way we build our cities: over time, without a plan, on top of ruins. - Ellen Ullman",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "To be a programmer is to develop a carefully managed relationship with error. - Ellen Ullman",
    "The best way to learn to code is to code. - Anonymous",
    "Don't worry if it doesn't work right. If everything did, you'd be out of a job. - Mosher's Law of Software Engineering",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code. - Dan Salomon",
    "There's nothing more permanent than a temporary hack. - Kyle Simpson",
    "The only code worth writing is code that makes your life easier. - Kent Beck",
    "It’s not about what you know, it’s about what you can figure out. - Anonymous",
    "Programming can be fun, so can cryptography; however, they should not be combined. - Kreitzberg and Shneiderman",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "If you want to be a better programmer, write more code. - Anonymous",
    "Java is to JavaScript as car is to carpet. - Chris Heilmann",
    "Controlling complexity is the essence of computer programming. - Brian Kernighan",
    "Good code is short, simple, and symmetrical - the challenge is figuring out how to get there. - Sean Parent",
    "The most important skill for a programmer is to be able to effectively communicate. - Anonymous",
    "Programs are meant to be read by humans and only incidentally for computers to execute. - Harold Abelson",
    "If you think math is hard, try programming. - Anonymous",
    "Before software can be reusable, it first has to be usable. - Ralph Johnson",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "The computer was born to solve problems that did not exist before. - Bill Gates",
    "It's not that I'm so smart, it's just that I stay with problems longer. - Albert Einstein",
    "The best error message is the one that never shows up. - Thomas Fuchs",
    "The best code is no code. - Jeff Atwood",
    "There are only two industries that refer to their customers as 'users'. - Edward Tufte",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. - Seymour Cray",
    "Talk is cheap. Show me the code. - Linus Torvalds",
    "The difference between theory and practice is that in theory, there is no difference between theory and practice. - Richard Moore",
    "If you optimize everything, you will always be unhappy. - Donald Knuth",
    "A program that produces incorrect results twice as fast is infinitely slower. - John Osterhout",
    "You can’t have great software without a great team, and most software teams behave like dysfunctional families. - Jim McCarthy",
    "If at first you don't succeed, try, try, try again. Then quit. There's no point in being a damn fool about it. - W.C. Fields",
    "If you don’t know what to do, call the debugger. - Anonymous",
    "Make it work, make it right, make it fast. - Kent Beck",
    "I'm not a great programmer; I'm just a good programmer with great habits. - Kent Beck",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
    "Code never lies, comments sometimes do. - Ron Jeffries",
    "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
    "It's not a bug - it's an undocumented feature. - Anonymous",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "Computers are good at following instructions, but not at reading your mind. - Donald Knuth",
    "Programming is the art of telling a computer what to do through a series of instructions. - Anonymous",
    "To iterate is human, to recurse divine. - L. Peter Deutsch",
    "Good code is its own best documentation. As you’re about to add a comment, ask yourself, ‘How can I improve the code so that this comment isn’t needed?’ - Steve McConnell",
    "A program is never less than 90% complete, and never more than 95% complete. - Terry Baker",
    "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Martin Golding",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. - Steve Jobs",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It's logic-based creativity. - John Romero",
    "If you don’t build your dreams, someone else will hire you to build theirs. - Tony Gaskins",
    "Don’t write better error messages, write code that doesn’t need them. - Jason C. McDonald",
    "If you want to be a good programmer, learn to think outside the box. - Antonis Tsagaris",
    "There are only two hard things in Computer Science: cache invalidation and naming things. - Phil Karlton",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "The best way to get a project done faster is to start sooner. - Jim Highsmith",
    "Experience is the name everyone gives to their mistakes. - Oscar Wilde",
    "Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live. - John Woods",
    "If at first you don’t succeed; call it version 1.0. - Anonymous",
    "A language that doesn't affect the way you think about programming is not worth knowing. - Alan J. Perlis",
    "Programmers are constantly making things more complicated than they need to be because future-proofing is impossible. - Edsger W. Dijkstra",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "The most disastrous thing that you can ever learn is your first programming language. - Alan Kay",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson and Gerald Jay Sussman",
    "The best code is no code at all. - Jeff Atwood",
    "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
    "It's not a bug - it's an undocumented feature. - Anonymous",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. - Patrick McKenzie",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis. - Alan Perlis",
    "Debugging is like being the detective in a crime movie where you are also the murderer. - Filipe Fortes",
    "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time. - Tom Cargill",
    "Code never lies, comments sometimes do. - Ron Jeffries",
    "Coding is not just code, that is a live thing to serve everyone! - Ming Qian",
    "The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie",
    "Software is a great combination of artistry and engineering. - Bill Gates",
    "Code is a journey, not a destination. - Anonymous",
    "There are two ways to write error-free programs; only the third one works. - Alan J. Perlis"
]
